### ISSUE TITLE
Hacktoberfest 2021: Add more examples

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/javagony-examples#2]
Javagony is a challenge to write Java *without* using `if`, `while`, `for`, `do`, `switch`, or ternary operators (` foo ? bar : baz`).
What you *can* use is `try {} catch () {}`, and recursion.

For example, instead of
```java
if (x == 0) {
  System.out.println("x is zero");
} else {
  System.out.println("x is not zero");
}
```
you would write
```java
try {
  int test = 1 / x; // Divide by zero error
  System.out.println("x is not zero");
catch (ArithmeticException xIsZero) {
  System.out.println("x is zero");
}
```

The challenge is to add some more examples of common algorithms and/or concepts implemented in Javagony.

Here are some to get started, but feel free to add your own if you think they will be interesting:

- [x] Fibonacci Sequence
- [x] Factorials

Feel free to view the other examples to get help.

## Fibonacci Sequence

This is a way to do a Fibonacci sequence in *normal* Java. But how would you do it if you can't use `if`, `switch`, etc.?

```java
// gets the nth number of the Fibonacci sequence
public static int fibonacci(final int n) {
  if (n < 0) {
    throw new IllegalArgumentException(Integer.toString(n));
  }
  switch (n) {
    case 0:
      return 0;
    case 1:
      return 1;
    default:
      return fibonacci(n - 1) + fibonacci(n - 2);
  }
}
```

## Factorial

This is a way to calculate a factorial. How would you do it without using `if`, `for`, etc.?

```java
// gets n!
public static int factorial(final int n) {
  if (n < 0) {
    throw new IllegalArgumentException(Integer.toString(n));
  }
  if (n == 0) {
    return 1;
  }
  return n * factorial(n - 1);
}
```

***Edit:*** Factorial and Fibonacci have been completed, but if you can think of an example to add I'll review and possibly merge. I'll accept refactoring of examples as well (for example, the Fibonacci sequence example has to declare `BooleanException` as thrown to compile, even though it doesn't actually throw it).

**Comment by srideviabhirami** [comment]
Would you need the implementation for factorial and finonacci in javagony ?

**Comment by spenserblack** [comment]
@srideviabhirami You can add those if you want
